git_upd: notify-send if path does not apply

diff --git a/git_upd b/git_upd
--- a/git_upd
+++ b/git_upd
@@ -16,3 +16,11 @@ REMOTE_DIR="${4:?"Remote directory not specified!"}"
 # conflicts with untracked files
 git -C "$LOCAL_DIR" diff "$GIT_BRANCH" | ssh "$REMOTE_HOST" " git -C '$REMOTE_DIR' reset --hard '$GIT_BRANCH' && git -C '$REMOTE_DIR' apply --index --whitespace=nowarn - "
 
+# get the exit status of the above command (even if the command within ssh fails, that is propagated to here)
+exit_status=$?
+if [ $exit_status -eq 0 ]; then
+    echo "Remote command succeeded (status 0)"
+else
+    echo "Remote command failed with status $exit_status"
+    notify-send "Uncommitted-changes-sync error" "${LOCAL_DIR}"
+fi
